# Dependency management {#dependency}

This chapter covers the tools for *dependency management*, meaning the installation of software with all of the other
software needed (the *dependencies*).  This chapter is in an odd location of the book. We should set you up with `conda`
early in the class, but describing it first seems to break the flow of earlier chapters.

Let's refer to a piece of software as a package. `conda` and `brew` exist as third-party package managers,
or tools to install packages, meaning that they exist alongside the native package manager for your operating
system (if one exists).

Tools like `conda` or `homebrew` are attempting to solve a very difficult problem.
In general, it is quite difficult to support thousands of different packages for multiple operating systems.  In the case of
R and Python packages, it is also very difficult to provide reliable packages for libraries for those languages that are 
compatible with multiple versions of each language.  Thus, none of these solutions are really perfect and things will
go wrong from time to time.  However, I expect that you will find them useful and they are certainly much easier
than maintaining installations of everything you need from source.

This chapter tries to solve a handful of interrelated problems:

* Most of our students/postdocs use Mac OS, which has no package manager for Unix tools.
* You may need to install software on Unix machines where you don't have "super user" privileges.
* You may need to have multiple versions of the same software on your system, or some other complexity
  requiring you to "wall off" the installation of one set of tools from another.

## conda {#conda}

Reasons to use `conda`:

* You do not need privileged ("superuser") access to your machine.  By default, things are installed
  in your `$HOME` directory.
* On systems like Apple's `macOS`, which has no package manager, you will now have one.
* Packages are compiled in a consistent manner helping to prevent incompatibilities.
* You may have multiple versions of the same software on your system via *environments*.
* It is available for Linux, `macOS`, and Windows

For those familiar with Python's `virtualenv` feature, `conda` is a generalization of that concept
to include software outside of the Python ecosystem.

The major alternative to `conda` is [homebrew](https://brew.sh/), which is available for Linux and `macOS`.

### What it does and does not do

Briefly, `conda` allows you to install packages, have multiple versions of those packages installed in different environments,
and "dump" a list of these environment contents to file.  These files can be used to recreate the same environment on
another machine of the *same* operating system.  `conda` does **not** allow the precise replication of environments
between *different* operating systems.  For example, you cannot create an environment on `macOS` and then expect to replicate 
it exactly on the Linux environment of the UCI HPC.  Simply put, there is no guarantee that the same versions of the same packages
are available at the same time for all operating systems (and with those packages having the same versions of the same dependencies).


### Getting conda

By `conda`, we really mean `miniconda`.  Get the latest Python 3 installer [here](https://docs.conda.io/en/latest/miniconda.html)
and follow the instructions.  Accept the defaults, unless you have good reason not to.

If you use the Ubuntu subsystem on Windows 10, then you actually want to download the *Linux* installer!

### Channels

There are different organizations, called *channels*, that supply `conda` packages.  An important 
channel is [Bioconda](https://bioconda.github.io/).  Follow the instructions at their site
to set up your channels correctly--the order matters!

If you use packages from `Bioconda`, please cite @Gruning2018-xc.

### Using conda

The main [documentation](https://docs.conda.io) site is quite good.  It is useful to search for the *command reference*
page within the main docs.

Key commands to know are:

* `conda install` to install packages
* `conda list` to list packages in the current environment
* `conda remove` to remove packages from the current environment
* `conda update` to update packages in the current environment

#### Environments

Managing environments is described in detail in the [documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html), which would be good to look over right now, so that you have an idea of what is possible.

In this section, I want to discuss examples of how environments may be useful.  In order for your results to be reproducible,
you need to be doing all of your analyses with the same versions of the various packages that you are using.  Therefore, one 
common use of environments is to create different environments for different projects.

You can also use environments to test if your results are sensitive to changing the versions of packages.  Briefly, you may `clone`
your current environment into a new one, then run `conda update` to update the new environment.  Once that is done, rerun some or
all of your analyses and see if the results are the same or not.  If not, maybe you can figure out why not. (This procedure could
actually reveal bugs in your code!)  Based on what you see, you can decide what to do next.  You can decide to stick with the old
or the new environment, and delete the other.

If your project is sufficiently complex, it may be useful to dump your environment's contents to a file and save that file as part of
the `git` repository for the project.  While it is unlikely that you will be able to recreate this precise environment in the future,
you'll have an idea of where to start.

A final use case involves your institution's compute cluster.  If you are allowed to install `conda` there, it may be a useful
way to manage dependencies for yourself.  There are several advantages to being able to do this. Here at UCI, it is possible
to install `conda` for yourself as a `module`, which we discuss in the lab portion of the course.

## brew {#brew}

**TBD**

## Containers (Docker, etc.)

**TBD**
