# Introduction

This book seeks to introduce "typical" early-stage PhD students in the biological sciences to computer skills that
will likely be necessary for them to complete their research.  By "typical", I mean someone who was probably a 
biology major as an undergraduate who now finds themselves doing research in a field where they have to write 
"scripts" or "programs" to get daily tasks accomplished.

In my corner of research at UC Irvine, I cannot imagine a student being able to complete their dissertation
without becoming proficient in languages such as [Python](http://www.python.org) and/or [R](http://www.r-project.org).
These programming languages are the subjects of Chapters \ref{Python} and \ref{R}, respectively, after a brief
general introduction to programming concepts in Chapter \ref{programming}.
Further, to make one's life a bit easier, there must be some way to change code that doesn't involve copying files,
editing, copying again, and eventually losing track of which version is the current one, or even the one that works.
An easier path does exist, in the form of "version control" software, such as [git](https://git-scm.com/).
It is becoming more common to require that code used for research be made publicly-available, meaning that students
need to be familiar with the various websites offering free services for code sharing.  These topics are covered
in Chapter \ref{git}.

Please read the chapter on objectives and expectations for the course, Chapter \ref{learningobjectives}.  Bear
in mind that this is a single ten week course on a huge topic. Thus, we cannot do everything.  In fact, we have
to completely punt on a lot of interesting and fun stuff!  Where possible, I mention such things and note that they are 
*BTS*, or beyond the scope of this course.

It is useful to keep in mind the ultimate goal of our research, which is to communicate it.  This communication
will take on many forms, from making plots (or tables) for yourself, for lab meeting, for a meeting with your advisor, for
presentation at a conference, for publication, etc..  The "quality" required (in terms of the clarity and technical detail
of the presentation) may differ for each of things, but one constant remains throughout.  You need a *reproducible* way of going
from "raw data" to the final "report".  The only reliable way to do this is to generate a pipeline of scripts that can take you
from start to finish.  Yes, this means no Adobe Illustrator, etc., as there is no way that "future you" will remember which mouse clicks 
were necessary.  In fact, one of the best motivations for generating reproducible computational work flows comes from pure
self-interest!  As other life events (TA-ing courses, etc.) cause you to walk away from your research, you need to be able to return
to your project in the future and quickly get back up to speed.  The topics covered in the later chapters will point you to 
concepts and techniques that you will likely find useful in documenting your research progress as well as in writing your dissertation.
