# Open source software and communities

It is likely that most of the software that you use for your research is *open source software*, or OSS.
The primary feature of OSS is that the source code is available.  This availability is key for finding bugs,
fixing bugs, distributing the software, and allows one to use, study, and modify the product.  A corollary 
feature of OSS is that it is often available free of charge.

Open source software is the product of open source communities, which is something that many people don't 
take the time to think about.

## Volunteer culture

Most OSS is developed, maintained, and supported entirely by volunteers.  In relatively rare cases, individuals
may be paid by companies to work on OSS, but most of the time, the work is being done by professionals in their
"spare" time.  It is important to acknowledge the volunteer status of the contributors for many reasons:

* It is amazing when the product is very high quality.  Linux, which is the OS for something like 90% of computers
  worldwide, is almost all-volunteer.  R and Python, too, at least in the early days.
* When something isn't working as you expect, or the documentation is lacking, then this too is a side-effect 
  of the volunteer labor force.  A lot of OSS software had its origins in solving a particular problem before
  being released to the public.  If the work became popular after its release, the resulting larger user
  base is guaranteed to find weaknesses.  In many cases, including for academic software, it becomes nearly
  impossible for one person to support such a large user base.  Thus, it becomes important that the community
  contribute back.
* It becomes important to learn how to interact with the community behind various OSS works.  I am not saying 
  that toxic behavior found in some communities is acceptable.  Rather, there are specific modes of communication
  used for discussing specific works, which is the topic of the next section.
  
## How to ask for help, report problems, etc.

If you have a question about an OSS work, then you need to know where to ask it, and *how* to ask it.  The *how*
is especially important when you have a problem getting something working.

There are many ways for you to interact with OSS developers, including:

* GitHub issues
* [Gitter](https://gitter.im/)
* IRC
* Mailing lists

It is important to note where to go, and to recognize that it varies from product to product.  Ideally, the
documentation will note the appropriate venue.  Note that Stack Overflow is not on the list.  I am not aware
of any OSS developers that monitors SO for questions about their projects.  But I am aware of many instances
where questions on SO were cross-posted to the "official" help channels, which is often viewed as not okay.
Cross posting is problematic because the answer often only appears in one place, making things confusing
for those who come later.

The *how* to ask a question is very important when you cannot get something to work or you think there is
a bug in a piece of software.  No one can help you if your question is vague or if it requires installing
a ton of software and having access to your raw data in order to see the issue.  What is needed here is a 
*minimal reproducible example*, or MRE.  The goal here is to construct a self-contained example that fails 
and send that to the author.  Yes, this takes more time than just saying, "I get an error on my data",
or "This 300 line R script with your tool in the middle isn't working", but the people volunteering their
time to work on this project have zero incentive to help out when issue descriptions are not well done. So,
if you want their help, then you probably have to help them out a bit, too.

The act of creating an MRE is often very useful.  Sometimes, it does show that there is indeed a bug of some
sort in the tool that you are using.  Other times, you find bugs in your own code that were the real cause of
the problem.

Please note that most OSS developers *welcome* the report of issues with their projects, especially when
they are well-crafted.  Most people want their work to be useful, and do sincerely want to help, even if
they have no time, no financial incentive, etc..

## Challenges of developing OSS software

@Siepel2019-av gives a thoughtful overview of the problems facing software development in the life sciences.
While the focus is on genomics, the problems are more general than that, as many of the incentive structures
in academia apply more broadly.
