# The Python programming language {#Python}

## Good books

For beginners, I recommend the Software Carpentry lessons (see Chapter \ref{programming}).
@McKinney2017-se and @VanderPlas2016-sn give a good overview of Python for "data science" applications. @Ramalho2015-fk
is an excellent book on intermediate to advanced Python programming.

## Strengths and weaknesses

Python is an excellent *general purpose* programming language, as opposed to a *domain specific* language that primarily
supports writing code for a limited set of tasks.  [Mathematica](https://www.wolfram.com/mathematica/) and [SAS](http://www.sas.com)
are examples of commercial, domain-specific languages, although the companies behind them would probably disagree.

Python is generally considered easy to learn, although any such statement is subjective.

On the community side, Python is a welcoming and inclusive community.  That doesn't mean that bad ideas won't get a 
"hard no" response, especially if you were to propose a change to the core language that is not well thought out.
What it does mean is that people are pretty good about responding to questions and helping people out, modulo the
usual concern with open source software that this sort of support is done entirely on a volunteer basis.

Regarding data-centric programming, Python is the current *lingua franca* of machine learning and artificial intelligence
tools.  It also supports object-oriented programming idioms, streamlining the design of more complex code bases. (The
object-oriented stuff is covered in @Ramalho2015-fk\.)

Python has one small and one big weakness, at least as far as we are concerned.  The small weakness is that Python
code is sensitive to the *white space* in your file, which makes it very different from most other languages.  This
means that the indentation in your code must be consistent, which actually forces you to write short lines of code
that are nicely-formatted.  However, it also freaks people out at first.  The solution to your spacing problem
is solved by your editor:

* Set a `tab` character to equal four spaces in length
* Set the `tab` command to insert spaces instead of a tab.

The combination of these two settings means that your file will display the same way in all editors, which is extremely
helpful when multiple people are collaborating.  For fun, you should now do a Google search on "silicon valley tabs 
versus spaces", if you haven't seen it already...

The bigger problem with Python is that a "data frame" type is not as well-developed as its R analog.  A data frame is,
for all intents and purposes, a representation of a spreadsheet in memory.  In other words, we have rectangular data
where columns represent variables and rows are observations of those variables.  I discuss this point more in 
\ref{pandas} below.

If you work more with Python, you'll eventually run into another weakness.  The standards required to package
your software for distribution via official channels such as [PyPi](http://www.pypi.org) are loose at best,
making distribution a somewhat frustrating endeavor.

## Python 2 vs 3

You must be using Python version 3, preferably 3.6 or later.  Python 2.7 is the last release of the 2.x series, 
and it is slated for end of life January 1, 2020, meaning that no more updates will happen. The major libraries
for Python, some of which are discussed below, have already dropped support for 2.7.

Note, installing Python 3 on Apple's OS X operating system is best done via `conda`.  See Chapter \ref{conda}.

## Python files

A file containing Python code ends with the suffix `.py`.

## Executing a script

To execute a set of commands in a script:

```{sh,eval=F}
python3 scriptname.py
```

On systems using `conda` (Chapter \ref{conda}) to provide Python 3, the following will work:

```{sh, eval=F}
python scriptname.py
```

## Shells

As an interpreted language, Python lets you work in an interactive shell.  The commands `python3` or `python`
will start that shell.  Once the shell is loaded, you can enter the same types of Python commands that
you would type into a script.  This shell is useful for playing around with ideas to get something working.

A nicer version of the shell is called [iPython](https://ipython.org/), which has more features and is the core
technology behind Jupyter notebooks (see Chapter \ref{notebooks}).

## Modules

Python libraries are called modules and are loaded via the `import` command:

```{python}
import numpy
```

The name `numpy` is a *namespace*, and using types in a module requires a reference via the namespace:

```{python}
a = numpy.arange(11)
print(a)
```

To save yourself some typing, you may provide a *namespace alias*.  For example, most people will import `numpy`
as follows:

```{python}
import numpy as np
a = np.arange(7) # Note the shorter namespace!
print(a)
```

## Useful types

The Python language provides a rich set of types for you to work with.  This section serves to name some of the more
common types.  See the official docs and/or online tutorials for more detail.

See Section \ref{types} to remind yourself of basic definitions.

### None

The NULL type in Python is called `None`:

```{python}
x = None
if x is None:
    print("yep, x is None!")
```

### str

Data consisting entirely of characters are represented as strings, or the `str` type:

```{python}
dna = 'AGCT'
type(dna)
```

String can be manipulated in various ways, see the [official docs](https://docs.python.org/3/library/stdtypes.html#text-sequence-type-str).

### Regular expressions

The `re` module provides regular expressions (regexes), which are a powerful way of searching and manipulating strings using patterns.
In general, regexes get complicated fast!

### bytes (what you may want instead of str)

The Python `str` type has a Unicode encoding, which is great for portably representing strings across systems using character
sets from different languages.  However, it is *not* the classical definition of a string, which is often taken to mean
a raw buffer of character data.  Such raw buffers are the `bytes` type:

```{python}
dna = b'AGCT'
type(dna)
```

A Google search of "python strings vs bytes" will take you to more on this topic.

### list

The `list` is the array-like type provided by the standard library:

```{python}
x = [1, 2, 3, 4]
type(x)
```

There are lots of fancy ways to create them:

```{python}
x = [i for i in range(1, 11, 2)]
x
```

You access elements via the `[]` operator.  In Python, the index if the first element is zero!

```{python}
x[0]
```

Python supports all sorts of fancy indexing:

```{python}
x[-1]
x[::2]
x[::-1]
```

Some notes:

* The types contained within a list need not all be the same
* The length of a list is given by the `len` function, which works for most containers in Python

### dict

The `dict` is the basic form of associative container:

```{python}
dna2rna = {'A':'U', 'G':'C', 'C':'G', 'T':'A'}
dna2rna['A']
rna = ""
for i in dna.decode('utf-8'):
    rna += dna2rna[i]
rna
```

Some hints about the above:

* We previously declared `dna` as a `bytes` object, but our `dna2rna` contains  `str` types.
* Thus, we need to decode the bytes to a string.

We could do the above entirely using `bytes` types, but it is more complex:

```{python}
dna2rna = {b'A':b'U', b'G':b'C', b'C':b'G', b'T':b'A'}
dna2rna[b'A']
rna = b'' 
for i in dna:
    rna += dna2rna[chr(i).encode()]
rna
```

It is useful to note that the `dict` is what you want when you need a fast lookup table.  However, there
is no guaranteed order:

```{python}
for key, value in dna2rna.items():
    print(key, value)
```


The output order happens to be the same as the input order here, but that will not be generally true.

If the order matters:

```{python}
import collections
ordered_dna2rna = collections.OrderedDict({b'A':b'U', b'G':b'C', b'C':b'G', b'T':b'A'})
for key, value in ordered_dna2rna.items():
    print(key, value)
```

### tuple

A `tuple` is an immutable collection:

```{python}
x = (1, 'abcd')
type(x)
```

The following code will trigger an error, and thus is commented out:

```{python, eval=F}
# x[0] = 2
```

Tuples are often used for returning multiple things from functions.


## Handling files and interaction with the operating system

The `sys` and `os` modules provide functions for talking to the OS.  The `glob` module is very handy for finding files based on
patterns such as `*.txt`.

Do not assume that functions in these modules have identical behavior on different operating systems, or even on different
versions of the same OS.  For example, `glob.glob` is documented to return the list of files in an "arbitrary order".  Thus,
if the order of the files matters to your work flow, you need to take the extra step to sort that list yourself according
to the desired criteria.

## Functions

Functions are defined using the `def` keyword:

```{python}
def add(x, y):
    return x+y

a = 1
b = 2
add(a, b)
```

Functions can have default values:

```{python}
def fxn_with_default(a = None): 
    return a

fxn_with_default()
fxn_with_default("Hello!")
```

The first function call doesn't print anything because it returns the NULL type `None`.

## Flow control idioms

### if/else

```{python}
x = 11
if x > 0 and x < 5:
    print ("condition 1")
elif x >= 5 and x < 32:
    print("condition 2")
else:
    print("condition 3")
```
    
### For loops

```{python}
sum = 0
for i in range(10):
    sum += i
print(sum)

x = [i for i in range(10)]
sum = 0
for i in x:
    sum += i
print(sum)
```

Note that the creation of `x` involved a `for` loop buried inside a *list comprehension*, which 
is a Python method for creating loops via one-liners.

### While loops

```{python}
isodd = True
i = 0
while isodd is True:
    if x[i] % 2 == 0.0:
        isodd = False
    print(x[i])
    i += 1
```

## Error handling

Python has two methods for reporting errors at run time.  The first is to "throw" an error object
called an `Exception`.  The second method is to `assert` that something is true.  The 
latter method can be disabled at runtime by invoking the Python interpreter with the "optimization
flag":

```{sh, eval=F}
python3 -O scriptname.py
```

### Exceptions

When an exception is thrown, the interpreter reports the type of the exception, the exception 
message, and what file/line number did the throwing.

In most cases, that is all that you need to know!  It is pretty obvious when an error occurs.

By way of example, let's use our `add` function from above, but we'll pass in two variables that cannot be added
together:

```{python}
try:
    add(1, "bananas")
except:
    print("Hmmm, that didn't work...")
```

We can get more info:

```{python}
try:
    add(1, "bananas")
except Exception as e:
    print(e)
```
### The `assert` statement

The `assert` statement is a useful way of saying "if this condition does not hold, abandon ship immediately".

The general form is:

```{python, eval=F}
assert condition, "Condition not met!"
```

For example (the following is unevaluated as it would prevent the book from being generated):

```{python, eval=F}
x = None
assert x is not None, "fatal error: value is None"
```

### Which to use?

Well, both!  But, if you want your user to be able to gracefully recover from an error, prefer exceptions.
In general, prefer exceptions and reserve `assert` for cases that really shouldn't happen.  I tend to sprinkle
`assert` statements into code that I am trying to debug.

## numpy

The **Num**meric **Py**thon library, or `numpy`, is a high performance array and numerical computing library. 
The name is pronounced "numb pie", but rhyming it with "lumpy" is a common mispronunciation.

`numpy` is implemented in C, and provides high-performance multidimensional arrays and linear algebra
functionality to Python.  Although it is not part of the standard library, it may as well be.

@VanderPlas2016-sn is an excellent introduction to `numpy`.

The fundamental type is the `array`:

```{python}
import numpy as np

x = np.array([1, 11, -10, 14])
x
x.dtype
```

The `dtype` is the numeric type stored by the array.  There is support for the full range of numeric types found in C:

```{python}
x = np.array([1, 11, -10, 14], dtype=np.float)
x.dtype
x = np.array([1, 11, -10, 14], dtype=np.int32)
x.dtype
x = np.array([1, 11, -10, 14], dtype=np.int8)
x.dtype
```

For C/C++ programmers, it is fine to be confused that `np.float` is the C/C++ `double`.  A complete list of valid `dtype`s
can be found online. (In fact, you can create your own using C or C++!)

The arrays can be multidimensional:

```{python}
x = x.reshape((2,2))
x
x.shape
```

Access is "C-major" by default, which means rows first, then columns:

```{python}
x[0,:] # row 0
x[1,:] # row 1
x[:,0] # column 0
x[:,1] # column 1
```

There is full support for matrix and vector maths.  However, the usual mathematical operators (`+`, `-`, etc.) work 
element-wise, and this don't give the expected results:

```{python}
x + 2
x * np.array([-1, 1], dtype=x.dtype)
```

To get the expected results from a vector-by-matrix operation, use the `dot` function:

```{python}
x.dot(np.array([-1, 1], dtype=x.dtype))
```

For a full list of `numpy` features, see the [home page](https://numpy.org/).

## scipy

`numpy` is a part of a larger community of scientific software for Python called [`scipy`](http://www.scipy.org).
In an ideal world, the former would provide the array types and some basic operations on them, and the latter would contain 
all of the numerical code.  The reality is that there is some feature overlap with both relying on the 
`numpy.array` as a fundamental type.  `scipy` contains code for all sorts of statistical calculations,
numerical optimization methods, etc.. In many ways, `scipy` adds a lot of the functionality found by default in R.

## Pandas (not the animal...) {#pandas}

The [pandas](https://pandas.pydata.org/) package provides a data frame object to Python plus many methods of operating on 
such objects.  See @McKinney2017-se for a good overview of the library.

`pandas` provides functions for getting data to/from files as well as to/from databases (see Chapter \ref{sqlite3}).
For example, let's read in the `mtcars` data that is commonly use for R examples:

```{python}
import pandas as pd
mtcars = pd.read_csv('data/mtcars.txt', sep='\t', index_col=0)
type(mtcars)
mtcars.head()
```

I like to describe the `pd.DataFrame` object as somewhere in between a spreadsheet and a database.  `pandas` relies quite a bit
on the idea that one of the columns is an index column, much like how databases work.  This behavior differs from the R `data.frame`
object (see Chapter \ref{R}).

Internally, the columns of a `pd.DataFrame` are `numpy` arrays.  Thus, they are high performance but do not have a universal notion
of a NULL value at the time of this writing.  For the latest, do a search for "panda missing data".

I personally use `pandas` routinely in my research.  However, I must acknowledge that it is an idiosyncratic package.  While it 
is a powerful tool, its interface is quirky, with the same or similar options having different names in different functions, etc..
Part of the problem is the usual one of open-source software: `pandas` was developed at a company for the analysis of time series 
financial data.  After open-sourcing it, the package quickly became very popular relative to the number of people working on it. 
The result is a package trying to catch up and evolve into a more polished state.  The project leader, Wes McKinney, even has a 
[blog post](https://wesmckinney.com/blog/apache-arrow-pandas-internals/) on what he doesn't like about `pandas`.

Acknowledging the issues described above, `pandas` provides powerful methods for analyzing data frames. There is a lot of 
attention to detail in the `pandas` code in terms of performance, meaning that many operations are very efficient.

There are methods to group data and summarise subsets:

```{python}
# Group by automatic or manual transmission and number of gears,
# getting the mean of remaining columns
g = mtcars.groupby(['am','gear']).mean()
g
```

There are also database-like methods for joining data frames together.

## Improving performance

Most of the time, Python code written using the Python standard library, `numpy`, and `pandas` will be "fast enough".
If you find yourself in a situation where you have a performance bottleneck, you can look at the following
tools that may help.

Note that none of these tools promise speedups!  In fact, you will often be wasting your time unless you *know*
where your performance problem comes from in your code!  The only way to do that is to *profile* your code, and
how to do that is BTS.  For all of these tools, the best use is targeted, meaning that you want to only replace
your bottleneck with the (hopefully) more efficient version.

### Cython

[Cython](http://www.cython.org) is a compiler that translates a Python-like syntax into C code and compiles it.
There is special support for `numpy` arrays and you may make "wrappers" to functions provided by C or C++ libraries,
although the C++ support is limited.

Fun tip: [CythonGSL](https://github.com/twiecki/CythonGSL) is a fairly complete interface to the [GNU Scientific Library](https://www.gnu.org/software/gsl/doc/html/).

### numba

[numba](https://numba.pydata.org/) attempts to compile Python code into machine code.  The basic premise is that you can 
take a function that is slowing down your code and get a faster compiled version.  The documentation suggests that you'll 
get the best results for code doing numeric operations.

### The C API

Python is written in C, and has a full C library that you can access.  Using this library, you can write Python modules
in a mixture of C and Python.  Generally speaking, this is *quite advanced*.

### pybind11

[pybind11](https://pybind11.readthedocs.io/en/stable/) is a C++ library allowing you to write Python modules in idiomatic C++.
The big feature is that it supports modern C++ standards, meaning C++11 or later.   I use `pybind11` for a lot of my research code.
It is a fantastic product.  Like the C API, this is an advanced topic.


