# Other programming languages of interest {#otherlanguages}

## C

C is a compiled language.  It is high-performance, has a small standard library, and is the *de facto* standard of the Unix world.
R and Python are both implemented in C.

At first glance, C looks like it has a shallow learning curve, but that is just a reflection of the small standard library.
The truth is that you need to manually manage all resources and do so in away that doesn't "leak" resources when errors occur.

## C++

C++ is a compiled language that initially added objects to C.  Now, it seems to support nearly every programming idiom on the planet.
It is a high-performance language with a very steep learning curve.  It is my language of choice for performance-oriented code.
Unlike C, resource management may be handled a bit more safely via objects.  Otherwise, it is a much more complex language, 
although also a much richer one.  Scott Meyer's books are essential texts for anyone working in C++.

## julia

[julia](http://www.julialang.org) is a kind of a hybrid of interpreted and compiled languages.  If your work involves solving systems of 
ODEs or PDEs, then you should investigate julia.  Colleagues of mine who do that sort of thing tell me that it 
makes [Matlab](https://www.mathworks.com/products/matlab.html) irrelevant.  As an added bonus, Chris Rackauckas developed the ODE/PDE 
parts of julia during his PhD work here at UCI.

## rust

[rust](https://www.rust-lang.org/) is a high-performance compiled language originally developed by Mozilla.  It intends to 
compete with C and C++ for high-performance programming.  The language is new, but quite intriguing.  Like C++, the learning
curve will be steep, but there is a lot to like in what I've read.  Expect to see biological software written in rust.
