# Necessary hardware and operating system {#requirements}

This class requires a laptop for the labs.  The idea is that using your own machine simulates a 
more realistic experience of getting research computing done.

Life will be easier if you have a machine that either is, or can emulate, a Unix-like environment.
In order of ease of use, the following operating systems will work:

* Linux.  Basically any up-to-date release of any distribution.  Please be sure to 
  have Python 3 installed.  Most distros default to Python 2, and 3 must be installed separately.
* Apple's `macOS`.  Preferably High Sierra or later.  A serious complication is that the file system
  is not case-sensitive, meaning that `File.txt` and `file.txt` are treated as the same thing.
  You absolutely *must* have the appropriate version of `Xcode` installed for your system and have
  taken the extra steps to install the command line tools for that version of `Xcode`.  It is
  up to you to look up the required steps for that. Section \@ref(osxquirks) details issues that
  you may run across with this platform.
* Windows.  If you use Windows, you will have the toughest time.  I think, but am not totally sure,
  that you will need Windows 10 (or later).  There are a variety of "terminal emulators" for Windows,
  and it will be up to you to find one that works.  Windows 10 supports the "Windows Subsystem 
  for Linux", which provides things like a `bash` shell in an environment based on the Ubuntu Linux
  distribution.

## Issues with Linux {#linuxquirks}

This is the home team OS for scientific computing. Most of your problems will be interacting
with collaborators using Microsoft Office, Adobe products, etc..

## Issues with `macOS` {#osxquirks}

This OS is slowly being locked down so that applications installed from sources other
than the App Store may run into issues.

### Lack of clarity about the best way to install certain tools

We will recommend `conda` in this course for package management, but that isn't always the right answer.
For example, `conda` contains packages for `Rstudio`, \LaTeX\, and some others, but I **do not**
recommend installing them this way onto `macOS`.  Rather, prefer the `.dmg` installers for these tools or,
in some cases, you need to use `brew`.

### Third party software after major updates

When you make a major update from one "named" release to the next (*i.e.*, `Mojave` to `Catalina`),
you should expect third party software (stuff not installed via the "App Store") to break.  It won't happen
all the time, and what does break could change each time, but stuff does break!  An incomplete
list of things to monitor includes:

* [MacTex](https://tug.org/mactex/), which is the typical way to get \LaTeX\ onto an `macOS` machine.
* Your `conda` and `brew` installations.
* [Inkscape](http://www.inkscape.org)
* Any software installed into `/usr/local` may be deleted!! `brew`, for example, and most/all
  Unix software installed from source that didn't go into a `conda` environment, assuming 
  that you installed `conda` into your user's home directory.

### Xcode

You need to remember to update `Xcode` with each major `macOS` update, too!  And, don't forget the command
line tools.

### Python 3

As of `Catalina` (10.15), `Xcode` ships with Python 2.  Future versions (10.16+) will do something different
with all Unix "scripting" languages like Python and Perl, but it remains to be seen what that is.  It seems
likely that they will not be installed by default, meaning you'll need to use something like `conda` or `brew`
to install them.

### Unreliable behavior of programs using X11/XQuartz

Unix programs with a graphical interface rely on the X11 graphics toolkit.  On `macOS`, this is provided
by [XQuartz](https://www.xquartz.org/).  It is not always straightforward to get programs using X11
to work on current `macOS` releases.  For example, if you install `imagemagick` via `conda`, then
the `display` program (which displays graphics on the screen) probably won't work.  Instead, you will
have to use the `open` command on the file, which will open `Preview`.  Other `imagemagick` binaries
that don't require `X11`, such as `convert`, work just fine in my experience.  (I have the 
same issues installing these programs via `brew`.)

## Issues with Microsoft Windows {#windowquirks}

I don't have enough experience with this platform to have any content here, but there are certainly 
issues!
