# Technical details behind this book {#techdetails}

This book is generated using the [bookdown](https://bookdown.org/) flavor
of [R markdown](https://rmarkdown.rstudio.com/), or `Rmd`.  While `Rmd` files 
are usually generated using [R Studio](https://rstudio.com/), I instead
use the following work flow:

* The .Rmd files are edited using [neovim](https://neovim.io/) with the following
  plugins related to `markdown`
    * vim-pandoc/vim-pandoc
    * vim-pandoc/vim-pandoc-syntax
    * vim-pandoc/vim-rmarkdown
  
  These plugins are from [vim-pandoc](https://github.com/vim-pandoc/).

* `git` integration in `neovim` is provided by [tpope/vim-fugitive](https://github.com/tpope/vim-fugitive).

* The book is built from .Rmd files using [GNU make](https://www.gnu.org/software/make/).

* The bibliographic entries are Bibtex files generated by outputting a folder from [Paper Pile](https://paperpile.com/),
  which is the only non-free software used.

This book is generated on a Linux operating system, most likely Pop! OS version 19.10 or later.

You can get the source code for this book [here](https://github.com/ThorntonLab/ComputerSkills4GradStudents/).
