name: Build and deploy manual

on:
  pull_request:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  buildbook:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.8]
        r: [4.1]
    defaults:
      run:
        shell: bash
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Cache dependancies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.local
          key: ${{ matrix.python }}-${{ hashFiles('book/requirements.txt') }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r }}

      - name: Test R
        run: Rscript -e 'print("hello")'

      - name: Install IRkernel 
        run: |
          install.packages('IRkernel')
          IRkernel::installspec()
        shell: Rscript {0}

      - name: Edit PATH
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          python -m pip install --user --upgrade -r book/requirements.txt

      - name: Build the book
        working-directory: book
        run: |
          make

      - name: Move built HTML book
        working-directory: book
        if: github.event_name == 'release'
        run: |
          mv _build/html ../book_output

      - name: Upload artifacts
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v1
        with:
          name: book_output
          path: book_output/

  deploy:
    name: deploy
    needs: buildbook
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          # Artifact name
          name: book_output # optional
          # Destination path
          path: book_output # optional
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS }} 
        with:
          build_dir: book_output/
